### ISSUE TITLE
computeSumFactors on different batch and then combining  ?

### ISSUE THREAD

**Issue by ahy1221** [LTLA/SingleCellThoughts#1]
Thank you very much for sharing such comments and thoughts!  That is very very helpful to let me further understand scran and simpleSingleCell workflow! 
I am wondering is that right to perform size-factor normalization on each batch and then combining data into a SingleCellExperiment object for further downstream analysis  ? 
Since the computeSumFactors uses a pooled strategy to estimate size factor, I am not sure that should I need to do normalization on a combined dataset or  just need to do normalization on different datasets with further batch correction method such as mnnCorrect ?

Thank you in advance

Yao

**Comment by LTLA** [comment]
If you have different batches, I would perform scaling normalization _within_ each batch (e.g., with `computeSumFactors`), and then perform batch correction between batches (e.g., with `mnnCorrect`). The two methods handle different types of technical bias; scaling normalization deals with for scaling biases that affect each cell differently but all genes in the same way, while batch correction deals with biases that affect each gene differently but all cells in the same way (within a given batch).

**Comment by ahy1221** [comment]
Thank you very much! 
Just for avoiding much more issues, I am also wondering that why shouldn't we use HVGs identified by decomposeVar() for denoisePCA() ? Is that any concerns here ?

**Comment by LTLA** [comment]
You can certainly do so. However, the hypothesis test used in `decomposeVar` has relatively low power for highly variable genes that are driven by upregulation in rare populations. I didn't want to lose these genes, hence the use of all genes above the trend for `denoisePCA` (see `scran/pc_selection`).

More generally, it is generally hard to distinguish genes that are genuinely upregulated in rare populations from noisy genes with stochastic outlier expression in one or two cells. From a given gene's perspective, these two possibilities yield the same effect. To handle this properly, we need to consider correlations across genes, i.e., random outliers are unlikely to occur in the same set of cells. This is the major advantage provided by PCA, in that it allows us to find correlated aspects of the variance.

I should add there isn't much motivation for performing error control at this stage. Knowing that you have a (nominal) 5% FDR in your set of HVGs does not provide a measure of the performance of that gene set for downstream exploratory analyses like clustering; this is because the FDR only describes specificity, not sensitivity. For all we know, we can easily control the FDR while discarding a whole bunch of interesting genes. Hypothesis testing is better suited for cases where the detection of a gene as a HVG is a conclusion in and of itself, rather than a stepping stone to cluster analysis (or whatever).

In any case, if you have enough cells, the choice won't really matter. This is because all of the genes above the curve will be significant, courtesy of the overpowered nature of the experiment and the fact that the tests for variance are usually anticonservative when their assumptions are (very easily) violated. 

Tests for variance also have an interesting quirk in that they prioritize HVGs that are real but uninteresting. This is because they usually operate on ratios of the observed:expected variance. Due to the mean-variance trend in real data, it is easier to get large ratios when the expected variance is small (e.g., at high abundances). Thus, the lowest p-values tend to be found in genes with small observed variances but even smaller expected variances, corresponding to small biological components.

Hence I don't use the p-values from `decomposeVar` much anymore.

**Comment by ahy1221** [comment]
Thank you very much ! 
After having some trying according to your recommendation, I am wring to give some feedbacsk.

Regarding the mnnCorrect() , it performs quite well for controlling confound effect in my experient. For example , it totally remove the effect caused by cells from different donors by looking at tSNE plot. However, the MNN Corrected expression value seems weired. It depends on the order of input correction matrics, and it can be negative value. This cause some problems for fitting trendVar() because the logcounts would not be negative value and the trendVar() or makeTechTrend() seems to have some distribution assumption.  And the denoisePCA() always give a bunch of PCs by using mnn corrected value (100 PCs in my dataset in about 6000 cells).

Another thing I want to know is the performance of denoisePCA(). Usually denosiePCA() would give more import PCs than JackStraw method (here I used Seurat implementation with logcounts expression value). The selection of PCs have a huge impact for downstream clustering. I was wondering what is a good practice to selection important PCs for clustering ？ Especially in the setting that we need to considering batch effect for different datasets

**Comment by LTLA** [comment]
> It depends on the order of input correction matrics,

Yes, the correction is dependent on the order of the input matrices. This is a consequence of how the method currently works, as corrected data from earlier batches are used to help correction of later batches. Ideally, you would order the batches to that batches with the most MNN pairs to the first batch are corrected first, and those with the fewest MNN pairs are corrected last. This isn't easy to figure out from the data, so we've relied on the user knowing which batches are more similar to each other. In practice, it doesn't seem to matter much unless you're throwing in very different data sets.

> and it can be negative value.

Yes, the corrected values can be negative, which is an inevitable consequence of subtracting vectors.

> This cause some problems for fitting trendVar()

I've never tried to use the MNN-corrected values in `trendVar` or `denoisePCA`. My suggested workflow is to apply `trendVar` or `makeTechTrend` to each batch _prior_ to the MNN correction, to identify the highly variable genes that I should be applying the correction on. In particular, you can use `combineVar` to get a single set of genes for the correction itself. I would then proceed straight to clustering from the corrected values, using only the HVGs to focus on the biological effects.

 We have tried running PCA on the corrected values and selecting the first few components, e.g., for _t_-SNE, but this seems to enrich for some residual batch effect (not all the time, but enough times to be concerning), which would defeat the purpose of doing the correction in the first place.

If you must denoise, I would suggest doing it in each batch prior to performing the correction. You can ask `denoisePCA` to return a low-rank approximation of the original log-expression values, which can be fed into `mnnCorrect`. I haven't actually tried this, though, so YMMV.

> Usually denosiePCA() would give more import PCs than JackStraw method

AFAIK, the Jackstraw method is designed to test for significant associations between a variable (gene expression) and a given set of latent variables (i.e., PCs), not to identify the number of significant PCs in the first place; that seems like a job for permutation testing. But in any case, the idea is presumably to use these p-values to determine whether the PCs explain more variance than they would under a null model of uncorrelated data, allowing one to choose a cut-off for the number of PCs.

This is fine and all, but keep in mind that thresholding on the p-values only controls specificity. In a DE analysis, for example, setting a 5% threshold on the FDR tells us that, on average, no more than 5% of detected DEGs are false positives. This is great for "end-point" results where I take my genes and validate them, as the FDR actually has some meaning for my validation success rate. However, for PC selection, the utility of error rates is less clear, as I'm not going to validate my PCs directly. (I'm also not sure how one would apply the FDR to PCs, or do any multiple testing correction for that matter.)

In fact, blindly controlling specificity will come at the cost of losing sensitivity, which is just as (or even more) important for single-cell data analysis. Yes, retaining too many PCs will result in some noisier data, which might obscure your biology; but if your prioritize specificity above all else, retaining too few PCs runs the risk of completely discarding your biology in the first place. To sum up, I'm not convinced that the use of p-values to choose the number of PCs is any better or worse than any other threshold.

> Especially in the setting that we need to considering batch effect for different datasets

See my comments above about batch effects (sometimes) getting enriched after PCA. I remember Evan Macosko giving a talk where he uses ICA and then discards ICs that were strongly correlated with the batch; this might be an okay approach, but it does assume that your population composition is mostly the same between batches, otherwise you will be discarding informative ICs.

**Comment by ahy1221** [comment]
Thanks for your quick replying !

>I would then proceed straight to clustering from the corrected values, using only the HVGs to focus on the biological effects. We have tried running PCA on the corrected values and selecting the first few components, e.g., for t-SNE, but this seems to enrich for some residual batch effect (not all the time, but enough times to be concerning), which would defeat the purpose of doing the correction in the first place.

This seems having some contradictory because the buildSNNGraph() performs PCA on the HVGs using corrected values before constructing the underlying cell-to-cell graph (at least it was done in the MNN2017 scripts). I tried to do the same thing on my data and I observed that using k = 10, d = 50  works far better than  using k = 10, d = NA. So the question is still that how to choose right `d` for graph-based clustering?  I also went through the analysis code from EmptyDrop2017 and I found that it seems that you are trying  to  evaluate the clustering result by the modularity score.

`cluster.mod <- clusterModularity(snn.gr, sce$Cluster, get.values=TRUE);
log.ratio <- log2(cluster.mod$observed/cluster.mod$expected + 1);
pheatmap::pheatmap(log.ratio, cluster_rows=FALSE, cluster_cols=FALSE,  color=colorRampPalette(c("white", "blue"))(100));
`

But so far I don't really understand how to use this score for further tuning the cluster parameters

**Comment by LTLA** [comment]
As I said, sometimes PCA plays nice with the corrected values, and sometimes it does not. If the PCA does not enrich for the batch effect in your dataset, then great, use it. If it does enrich for a batch effect, then don't use it. It's that simple; not much of a contradiction there.

I don't really know how you're assessing "better" or "worse" here. Is this simulated data? Unless you have a ground truth, this discussion is meaningless. (And vague prior expectations on cell type relationships from wet lab collaborators don't count as a ground truth, at least not to me.)

I don't think there is such a thing as a "right" `d`, at least not in PCA. Even when you know the true rank, the first few eigenvectors will be skewed by random noise, meaning that you will need more PCs than the true rank to recover all of the basis vectors. (Factor analysis might be another story, as this actually involves trying to estimate the factors.) There is, however, a "reasonable" `d`; for this, you can have a look at the choice of `d` in each individual batch, and take the maximum across batches to use the `buildSNNGraph`. Or you can just stick with 50. Or 20. Or 10, or 100. By definition, clustering is  exploratory data analysis, so there's not really a right or wrong answer here; the priority is to get some observations to form a useful hypothesis **that you can take back into the lab and validate**.

The clustering modularity serves the same purpose as silhouette width plots/dendrograms in hierarchical clustering; to (i) check that the clusters are well separated based on their observed/expected modularity scores, and (ii) to see which clusters are more related to each other, and thus are candidates for merging. You could fiddle with the parameters to maximize the score (sum of the diagonals of `observed`), but this is only a rough guide; such an approach will favour maximizing the modularity of large clusters that contribute most, which might result in loss of resolution for smaller clusters. 

All in all, it seems you are intent on trying to get all your parameters set up perfectly. Don't worry about it. I mean, in a population of immune cells, what is the "correct" clustering anyway:

- Separation of T, B cells and other major cell types
- Separation of CD4+, CD8+, DP, DN T cells; memory B, plasma B, etc.
- Separation into the million different T/B/whatever cell subsets beloved by immunologists

All of these clusterings would be "correct", just at differing resolutions. I could also imagine that, by using different features or with a different clustering method, you would get different looks at the data, e.g., clustering by activation status, metabolic activity, cell cycle, stress. All of which would be "correct", or at least interesting. So... measure once, cut twice, and get something useful back to the wet lab people that they can check with independent experiments. Personally, a scRNA-seq paper with a strong series of functional experiments at the end is far more convincing than endless fiddling with the data.
