### ISSUE TITLE
Complex design for future t-test-based marker finding 

### ISSUE THREAD

**Issue by ahy1221** [LTLA/SingleCellThoughts#2]
I think one of advantages of limma-based marker finding is that people can provide design matrix for correcting batch or cell-cycle effect while doing differential expression analysis.
Do you think this would be a problem ? Or do you have any simulations for that ?

**Comment by LTLA** [comment]
Yes, that is definitely an advantage, and that's why I initially designed `findMarkers` to use _limma_ (and that's why it can still use linear models if you supply it with a `design=` matrix). 

However, most of the time, there are no additional blocking factors, which negates the major advantage of linear models. Instead, you have to pay the price of having to deal with variance-related issues mentioned in `scran/marker_detection/comments.Rmd`. Hence the current defaults.

Batch effects can be handled using the `block=` argument, which performs pairwise t-tests within blocking levels to avoid cross-block comparisons. This is more robust to model misspecification and/or differences in variances between clusters (especially due to zeroes) than using linear models.

**Comment by ahy1221** [comment]
Thank you! It is good to know the  block= argument will be retained in the future version.
Could you give more commnents about why model misspecification is worst than lack of model specification ? What if the situation is that there is a block having very small sample size ( for example only 5-10 cells in a block) ?

**Comment by LTLA** [comment]
Keep in mind that the cluster identities are themselves part of the model. If your clustering fails to split two clusters apart, you'll end up with a group that has much larger apparent variance in gene expression. This is what I mean by "model misspecification", as the cluster IDs are not correctly specified.

In and of itself, this is okay as we do not expect clustering to be perfect. However, in a linear model, the same variance estimate (for each gene) is used for all comparisons between clusters. This means that a comparison between two clusters will be affected by incomplete clustering of a third, unrelated cluster.  Good marker genes in the first comparison may not show up if they are DE _within_ the third cluster.

A related issue is that of zeroes. If many clusters are silent for a gene, the variance estimate for the gene is effectively shrunk towards zero (because the variance of zero expression is... zero). This means that, for comparisons between two clusters that do express the gene, genes with relatively poor separation may be favoured due to the lower variance. We avoid this with pairwise Welch t-tests.

If you have very few cells in a block, then you won't have a lot of information to find DEGs. It is true that the linear model will be more powerful here, as it shares information across blocking levels. However, this must be weighted against the issues mentioned above. In any case, I find it hard to believe that you'd be sequencing 5-10 cells in a batch - even for plate-based methods, I would be expecting 96 cells per plate.
